### ISSUE TITLE
after install robotframework-httplibrary show error in console

### ISSUE THREAD

**Issue by ghost** [peritus/robotframework-httplibrary#2] opened 2012-02-28 23:14 UTC
RIDE 0.42.1 running on Python 2.6.5.
Robot Framework 2.7 b1 (Python 2.6.5 on win32)

```
pip install --upgrade robotframework-httplibrary
pybot --test "xxxx" "F:\trabajo\test1-2"
...
3 tests total, 3 passed, 0 failed
==========================================================================================
.....
Report:  .....
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python26\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python26\lib\logging\__init__.py", line 1508, in shutdown
    h.flush()
  File "C:\Python26\lib\logging\__init__.py", line 754, in flush
    self.stream.flush()
  File "C:\Python26\lib\StringIO.py", line 256, in flush
    _complain_ifclosed(self.closed)
  File "C:\Python26\lib\StringIO.py", line 40, in _complain_ifclosed
    raise ValueError, "I/O operation on closed file"
ValueError: I/O operation on closed file
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python26\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python26\lib\logging\__init__.py", line 1508, in shutdown
    h.flush()
  File "C:\Python26\lib\logging\__init__.py", line 754, in flush
    self.stream.flush()
  File "C:\Python26\lib\StringIO.py", line 256, in flush
    _complain_ifclosed(self.closed)
  File "C:\Python26\lib\StringIO.py", line 40, in _complain_ifclosed
    raise ValueError, "I/O operation on closed file"
ValueError: I/O operation on closed file
```

**Comment by peritus** [comment] 2012-02-29 12:18
Thanks for the report!

I had this once on the continous integration server: http://code.google.com/p/robotframework/issues/detail?id=995#c6 (also related bug, maybe in robotframework itself?). 

Can you provide more info (e.g. your tests) on how this happens ? Does the error occor every time you execute this test ? Would be great to have this reproducible!

**Comment by ghost** [comment] 2012-02-29 21:50
yes , the problem is when import the library HttpLibrary.HTTP in resource and in suite.
in both.

**Comment by criz1211** [comment] 2012-03-07 14:45
Hi,

I too face similar problem.
Just by adding the HttpLibrary.HTTP in the suite, i get this error.
I get this error even if i dint use any of its keywords or any references in the test cases.

I use Robot Framework 2.6.0 with Python 2.6.6.

**Comment by peritus** [comment] 2012-03-07 14:51
Related: "Issue with RotatingFileHandler logging handler on Windows " http://bugs.python.org/issue4749

**Comment by peritus** [comment] 2012-03-07 14:54
@criz1211 @jrvilda Could you test this with robotframework 2.7 ? Alpha 1 has this fix https://code.google.com/p/robotframework/issues/detail?id=985 included, this looks like a perfect match for the problem.

rf-httplib uses the "python standard logging" that's new. Unfortunately I don't have a windows machine set up for development.

**Comment by peritus** [comment] 2012-03-07 14:58
@jrvilda I see you're already using RF 2.7 b1 .. I have no idea whether this is rf-httplib-specific, it certainly seems windows-specific. I'll ping the @robotframework guys.

**Comment by pekkaklarck** [comment] 2012-03-07 22:41
Do I get it right that this happen consistently on Windows but doesn't happen elsewhere? I try to remember to test this tomorrow when I'm at the office and have an access to a Windows box. If there's a reproducable bug in Robot itself, we ought to be able to fix it for RF 2.7 rc 1.

**Comment by yanne** [comment] 2012-03-08 08:18
@jrvilda @criz1211 Which Windows version you are using?

I don't get any errors in Win XP with Python 2.7

**Comment by peritus** [comment] 2012-03-08 10:50
This might not be windows-specific after all:

http://travis-ci.org/#!/peritus/robotframework-httplibrary/jobs/820794/L410 (a linux box, note that the tests don't fail but simply print out the same stack trace after they all passed)

```

Tests.Json                                               | PASS |
40116 critical tests, 16 passed, 0 failed
40216 tests total, 16 passed, 0 failed
403=================================================================
404Tests                                                    | PASS |
40559 critical tests, 59 passed, 0 failed
40659 tests total, 59 passed, 0 failed
407=================================================================
408Output:  /home/vagrant/builds/peritus/robotframework-httplibrary/output.xml
409Log:     /home/vagrant/builds/peritus/robotframework-httplibrary/log.html
410Report:  /home/vagrant/builds/peritus/robotframework-httplibrary/report.html
411Error in atexit._run_exitfuncs:
412Traceback (most recent call last):
413  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
414    func(*targs, **kargs)
415  File "/usr/lib/python2.6/logging/__init__.py", line 1516, in shutdown
416    h.flush()
417  File "/usr/lib/python2.6/logging/__init__.py", line 762, in flush
418    self.stream.flush()
419  File "/usr/lib/python2.6/StringIO.py", line 256, in flush
420    _complain_ifclosed(self.closed)
421  File "/usr/lib/python2.6/StringIO.py", line 40, in _complain_ifclosed
422    raise ValueError, "I/O operation on closed file"
423ValueError: I/O operation on closed file
424Error in sys.exitfunc:
425Traceback (most recent call last):
426  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
427    func(*targs, **kargs)
428  File "/usr/lib/python2.6/logging/__init__.py", line 1516, in shutdown
429    h.flush()
430  File "/usr/lib/python2.6/logging/__init__.py", line 762, in flush
431    self.stream.flush()
432  File "/usr/lib/python2.6/StringIO.py", line 256, in flush
433    _complain_ifclosed(self.closed)
434  File "/usr/lib/python2.6/StringIO.py", line 40, in _complain_ifclosed
435    raise ValueError, "I/O operation on closed file"
436ValueError: I/O operation on closed file
437
438Done. Build script exited with: 0
```

doesn't seem deterministic, though.

Btw, contrary to my earlier claims, rf-httplib does not use "import logging" but "from robot.api import logger" https://github.com/peritus/robotframework-httplibrary/blob/master/src/HttpLibrary/__init__.py#L1 ..

**Comment by peritus** [comment] 2012-03-08 11:34
Seems to be python-2.6 specific. Look at http://travis-ci.org/#!/peritus/robotframework-httplibrary/builds/820920 (and maybe the previous builds)

All those with windows machines, could you try whether python 2.6 vs. 2.7 makes a difference ?

**Comment by yanne** [comment] 2012-03-08 13:22
We managed to find the root cause for the Traceback.

It seems that webtest registers a StreamLogger that writes to stderr. The registartion happens during library init, at which point RF has replaced stderr with a StringIO instance. Later, after sys.exit() has been called and that logger is closed it tries to close the already closed StringIO instance, which fails and causes the traceback.

The failure occurs with Python 2.5 and 2.6 but not with 2.7.

Luckily, the fix is quite easy, and will be include in RF 2.7. Here's the related issue https://code.google.com/p/robotframework/issues/detail?id=1079.

I think this issue should be closed, since it cannot be fixed in httplibrary

**Comment by pekkaklarck** [comment] 2012-03-08 13:29
It would be possible to add the same fix to HTTPLibrary too. That would suppress the traceback when using the library with earleir Robot versions. The fix is pretty simple:

```
import logging
logging.raiseExceptions = False
```

**Comment by ghost** [comment] 2012-03-08 14:23
resolved with robotframework-2.7rc1

**Comment by peritus** [comment] 2012-03-08 16:01
Wow, thanks for the quick resolution (and the -rc1!).

Won't include the `raiseExceptions = False` in the lib as I consider it bad style (modifying globals, etc.) — but everyone encountering that (and wanting to use old versions of python and robot framework) is encouraged to include the two lines in his/her bootstrapping code.

**Comment by peritus** [comment] 2012-03-08 16:02
BTW, rf-httplib is now tested against -rc1 on @travis http://travis-ci.org/#!/peritus/robotframework-httplibrary — looks good so far.

**Closed as completed by peritus** 2012-03-08 16:01 UTC

**Comment by pekkaklarck** [comment] 2012-03-08 17:08
@peritus, pretty much all configuration to logging has, by design, global effects. I agree that in this case adding the workaround for others bugs in httplib isn't needed, though, especially since the problem doesn't appear with Python 2.7 or RF 2.7.

If someone has motivation, a bug could be opened to WebTest for registering StreamHandler with sys.stderr that others may have intercepted. They should use `sys.__stderr__` instead. StreamHandler uses sys.stderr by default (which IMHO is a bug too) but WebTest actually passes sys.stderr explicitly, at least, here:
https://bitbucket.org/ianb/webtest/src/63d9903c478b/webtest/sel.py

**Comment by criz1211** [comment] 2012-03-09 14:06
Thanks a lot everyone!

It helps me a lot to fix this problem.
